export const REQUEST_HOUSE_LIST = 'REQUEST_HOUSE_LIST';
export const FETCH_HOUSE_LIST = 'FETCH_HOUSE_LIST';
export const RECEIVE_HOUSE_LIST = 'RECEIVE_HOUSE_LIST';
export const RECEIVE_SELECTED_HOUSES = 'RECEIVE_SELECTED_HOUSES';
export const REQUEST_TITLE_ALIAS = 'REQUEST_TITLE_ALIAS';

export const REQUEST_GROUP_LIST = 'REQUEST_GROUP_LIST';
export const RECEIVE_GROUP_LIST = 'RECEIVE_GROUP_LIST';
export const REQUEST_ADD_HOUSES_TO_GROUPS = 'REQUEST_ADD_HOUSES_TO_GROUPS';
export const REQUEST_CREATE_GROUP = 'REQUEST_CREATE_GROUP';

export const REQUEST_MESSAGE_LIST = 'REQUEST_MESSAGE_LIST';
export const RECEIVE_MESSAGE_LIST = 'RECEIVE_MESSAGE_LIST';
