/** 房源相关 */
export const REQUEST_HOUSE_LIST = 'REQUEST_HOUSE_LIST';
export const FETCH_HOUSE_LIST = 'FETCH_HOUSE_LIST';
export const RECEIVE_HOUSE_LIST = 'RECEIVE_HOUSE_LIST';
export const RECEIVE_SELECTED_HOUSES = 'RECEIVE_SELECTED_HOUSES';
export const REQUEST_TITLE_ALIAS = 'REQUEST_TITLE_ALIAS';

/** 组相关 */
export const REQUEST_GROUP_LIST = 'REQUEST_GROUP_LIST';
export const RECEIVE_GROUP_LIST = 'RECEIVE_GROUP_LIST';
export const REQUEST_ADD_HOUSES_TO_GROUPS = 'REQUEST_ADD_HOUSES_TO_GROUPS';
export const REQUEST_CREATE_GROUP = 'REQUEST_CREATE_GROUP';

/** 消息相关 */
export const REQUEST_THREAD_LIST = 'REQUEST_THREAD_LIST';
export const RECEIVE_THREAD_LIST = 'RECEIVE_THREAD_LIST';
export const FETCH_MESSAGE_LIST = 'FETCH_MESSAGE_LIST';
export const REQUEST_MESSAGE_LIST = 'REQUEST_MESSAGE_LIST';
export const RECEIVE_MESSAGE_LIST = 'RECEIVE_MESSAGE_LIST';
export const REQUEST_QUICK_REPLY_LIST = 'REQUEST_QUICK_REPLY_LIST';
export const RECEIVE_QUICK_REPLY_LIST = 'RECEIVE_QUICK_REPLY_LIST';
